apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.api.name }}-service-account
  namespace: {{ .Values.api.namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.api.name }}-role
  namespace: {{ .Values.api.namespace }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.api.name }}-role-binding
  namespace: {{ .Values.api.namespace }}
subjects:
  - kind: ServiceAccount
    name: job-launcher
    namespace: {{ .Values.api.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.api.name }}-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pentest-api
  namespace: {{ .Values.api.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.name }}
    spec:
      serviceAccountName: {{ .Values.api.name }}-service-account
      containers:
        - name: {{ .Values.api.name }}
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: PENTEST_IMAGE
              value: <your-ecr-url>/pen_test:latest
---
apiVersion: v1
kind: Service
metadata:
  name: pentest-api
  namespace: {{ .Values.api.namespace }}
spec:
  selector:
    app: {{ .Values.api.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
